on:
  push:
    branches: [main]
    paths:
      - 'books/zh-CN/**/*.md'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ao3
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm
      - name: Cache node_modules based on Markdown files
        uses: actions/cache@v2
        with:
          path: |
            node_modules/.cache
          key: ${{ runner.os }}-nodecache-${{ hashFiles('books/zh-CN/**/*.md') }}
          restore-keys: |
            ${{ runner.os }}-nodecache-
      - name: Publish to Ao3
        run: |
          echo "Publishing to Ao3, env: $AO3_COOKIE"
          pnpm mark-magic --task publishToAo3
        env:
          AO3_COOKIE: ${{ secrets.AO3_COOKIE }}
